### ISSUE TITLE
大佬，我安装总出问题

### ISSUE THREAD

**Issue by only8578** [F6JO/Suture_Box#6]
Traceback (most recent call last):
  File "/home/kali/SutureBox/suturebox.py", line 64, in <module>
    print(Get_list()) if args.list else main(target,modular,tool,info,single,exclude,output_file,down,proxy) # 若有-list则打印列表
  File "/home/kali/SutureBox/suturebox.py", line 49, in main
    dow_rep(down)
  File "/home/kali/SutureBox/controller/controller.py", line 102, in dow_rep
    Dow.get_tool(i)
  File "/home/kali/SutureBox/method/Download_tools.py", line 109, in get_tool
    for i in moud:
TypeError: 'NoneType' object is not iterable
求解决办法

**Comment by F6JO** [comment]
师傅，最近在hw，空了我修复一下

**Comment by only8578** [comment]
我把你那个tools-main文件夹下载下来后把那两个文件夹复制到suture_box-main下面tools文件夹里了，好像能用了，反正是没有报错。我是小白



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月19日(周二) 下午2:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [F6JO/Suture_Box] 大佬，我安装总出问题 (Issue #6)




 
师傅，最近在hw，空了我修复一下
