### ISSUE TITLE
师傅，有点问题下载文件的时候超出递归次数。

### ISSUE THREAD

**Issue by pzp12** [F6JO/Suture_Box#9]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users//Downloads/Suture_Box-main/method/Download_tools.py", line 23, in get_dir
    fanhui = requests.get(do,verify=False,proxies=self.proxies)
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Downloads/Suture_Box-main/suturebox.py", line 64, in <module>
    print(Get_list()) if args.list else main(target,modular,tool,info,single,exclude,output_file,down,proxy) # 若有-list则打印列表
  File "/Users/Downloads/Suture_Box-main/suturebox.py", line 49, in main
    dow_rep(down)
  File "/Users/Downloads/Suture_Box-main/controller/controller.py", line 102, in dow_rep
    Dow.get_tool(i)
  File "/Users/Downloads/Suture_Box-main/method/Download_tools.py", line 108, in get_tool
    moud = self.get_dir(self.url)
  File "/Users/Downloads/Suture_Box-main/method/Download_tools.py", line 27, in get_dir
    self.get_dir(do)
  File "/Users/Downloads/Suture_Box-main/method/Download_tools.py", line 27, in get_dir
    self.get_dir(do)
  File "/Users//Downloads/Suture_Box-main/method/Download_tools.py", line 27, in get_dir
    self.get_dir(do)
  [Previous line repeated 993 more times]
RecursionError: maximum recursion depth exceeded

**Comment by F6JO** [comment]
你好师傅，HW结束后我抽空修复一下，可以先手动下载 
在根目录新建tools目录，将https://github.com/F6JO/Suture_Box_tools 的两个文件夹放进去即可

**Comment by pzp12** [comment]
师傅加过了，还是不行的

**Comment by F6JO** [comment]
报什么错

**Comment by pzp12** [comment]
Traceback (most recent call last):
  File "/Users/Downloads/Suture_Box-main/suturebox.py", line 64, in <module>
    print(Get_list()) if args.list else main(target,modular,tool,info,single,exclude,output_file,down,proxy) # 若有-list则打印列表
  File "/Users/Downloads/Suture_Box-main/suturebox.py", line 50, in main
    Repeater(modular,tool)    # 进入中继模块
  File "/Users/Downloads/Suture_Box-main/controller/controller.py", line 23, in __init__
    for i in no_tool[1]:
TypeError: 'NoneType' object is not iterable

**Comment by F6JO** [comment]
执行的命令行可以发一下嘛师傅，hvv结束我抽空搞一下

**Comment by pzp12** [comment]
python3 suturebox.py -u https://127.0.0 <https://127.0.0.0/>.1  -m vulmap
感谢师傅了，不过好像什么命令都是报这个错
